// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace Src
{
    public partial class CnDateTest
    {
[TestMethod]
[PexGeneratedBy(typeof(CnDateTest))]
[ExpectedException(typeof(ArgumentOutOfRangeException))]
public void ConstructorThrowsArgumentOutOfRangeException804()
{
    CnDate cnDate;
    cnDate = this.Constructor(default(DateTime));
}
[TestMethod]
[PexGeneratedBy(typeof(CnDateTest))]
[ExpectedException(typeof(ArgumentOutOfRangeException))]
public void ConstructorThrowsArgumentOutOfRangeException928()
{
    CnDate cnDate;
    cnDate =
      this.Constructor(new DateTime(4611686018427387903L & 2020743265193295872L, 
                                    (DateTimeKind)(2020743265193295872uL >> 62)));
}
[TestMethod]
[PexGeneratedBy(typeof(CnDateTest))]
[ExpectedException(typeof(ArgumentOutOfRangeException))]
public void ConstructorThrowsArgumentOutOfRangeException821()
{
    CnDate cnDate;
    cnDate =
      this.Constructor(new DateTime(4611686018427387903L & 1009821702032457728L, 
                                    (DateTimeKind)(1009821702032457728uL >> 62)));
}
[TestMethod]
[PexGeneratedBy(typeof(CnDateTest))]
[ExpectedException(typeof(ArgumentOutOfRangeException))]
public void ConstructorThrowsArgumentOutOfRangeException146()
{
    CnDate cnDate;
    cnDate =
      this.Constructor(new DateTime(4611686018427387903L & 126227425208827904L, 
                                    (DateTimeKind)(126227425208827904uL >> 62)));
}
    }
}
