// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace Src
{
    public partial class CryptorTest
    {
[TestMethod]
[PexGeneratedBy(typeof(CryptorTest))]
[PexRaisedException(typeof(ArgumentNullException))]
public void Create01ThrowsArgumentNullException767()
{
    ICryptor iCryptor;
    iCryptor = this.Create01((string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(CryptorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void Create01ThrowsArgumentNullException407()
{
    ICryptor iCryptor;
    iCryptor = this.Create01("");
}
[TestMethod]
[PexGeneratedBy(typeof(CryptorTest))]
public void Create01510()
{
    ICryptor iCryptor;
    iCryptor = this.Create01("\0");
    Assert.IsNotNull((object)iCryptor);
}
    }
}
