// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace Src
{
    public partial class FileHelperTest
    {
[TestMethod]
[PexGeneratedBy(typeof(FileHelperTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void GetPhysicalPathThrowsArgumentNullException927()
{
    string s;
    s = this.GetPhysicalPath((string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(FileHelperTest))]
[ExpectedException(typeof(ArgumentException))]
public void GetPhysicalPathThrowsArgumentException938()
{
    string s;
    s = this.GetPhysicalPath("\0");
}
[TestMethod]
[PexGeneratedBy(typeof(FileHelperTest))]
[ExpectedException(typeof(ArgumentException))]
public void GetPhysicalPathThrowsArgumentException514()
{
    string s;
    s = this.GetPhysicalPath("");
}
[TestMethod]
[PexGeneratedBy(typeof(FileHelperTest))]
[ExpectedException(typeof(ArgumentException))]
public void GetPhysicalPathThrowsArgumentException738()
{
    string s;
    s = this.GetPhysicalPath("\0\0");
}
[TestMethod]
[PexGeneratedBy(typeof(FileHelperTest))]
public void GetPhysicalPath11501()
{
    string s;
    s = this.GetPhysicalPath("~");
    Assert.AreEqual<string>("D:\\Program Files (x86)\\Microsoft Pex\\bin\\", s);
}
    }
}
